### ISSUE TITLE
Can't open Local Media files

### ISSUE THREAD

**Issue by H-Swaya** [arianneorpilla/jidoujisho#403]
Can't open Local Media files because the button does nothing

![Screenshot_20240917_163040.jpg](https://github.com/user-attachments/assets/13220e56-f256-4f4b-847e-0a21c70b4e9f)

Jidoujisho Version 2.8.9
Samsung SM-A045F
Android 14
OneUI 6.1
Webview latest version
All permissions granted

**Comment by avc1657** [comment]
Idk, maybe try reinstalling?

**Comment by H-Swaya** [comment]
> Idk, maybe try reinstalling?

I did already, I tried out the 2.9.0 previews and ver 2.8.8 and 2.8.7 and still have the same issue

**Comment by H-Swaya** [comment]
Fixed it, I had a corrupted micro sd card that wasn't mounted, and removing it fixed it. Any unmounted micro SD card prevents the file explorer from popping up.
