### ISSUE TITLE
Video fetch from youtube could not be played. 

### ISSUE THREAD

**Issue by Surtr-sys** [arianneorpilla/jidoujisho#409]
This is an universal problem as I have asked my friends and they got the same problem, we all use 2.8.9 version, the video fetch from youtube couldnt be played as expected. 
I hope you could fix this asap. Thank!

**Comment by LukeThirlwell** [comment]
Same problem here. I'm using version 2.9.0 preview 2 and haven't been able to see any youtube  video for days.

**Comment by avc1657** [comment]
2.8.9 here. Doesn't work as well.

**Comment by WickedWhisperer** [comment]
Same issue here. It's not just YouTube. Even Network Streaming isn't working

**Comment by cosmicplatano** [comment]
Same here! 2.8.9

**Comment by arianneorpilla** [comment]
This should be fixed in [**2.9.0-preview3**](https://github.com/arianneorpilla/jidoujisho/releases/tag/2.9.0-preview3). Let me know otherwise.
