### ISSUE TITLE
Watching videos via YouTube literally doesn't work anywhere

### ISSUE THREAD

**Issue by Daii1414** [arianneorpilla/jidoujisho#412]
I am facing the same error as others here and have tried literally ALL versions of this app on different devices(Redmi note 10 pro, Samsung note 10, Samsung s22ultra) and nowhere does this feature work. 
I did everything as told and even more, but YouTube still didn't work. Stop advising people to roll back to the previous version if this advice doesn't work

**Comment by arianneorpilla** [comment]
This should be fixed in [**2.9.0-preview3**](https://github.com/arianneorpilla/jidoujisho/releases/tag/2.9.0-preview3). Let me know otherwise.
