### ISSUE TITLE
YouTube doesn't work

### ISSUE THREAD

**Issue by Calm99999** [arianneorpilla/jidoujisho#417]
It doesn't depend on a version or a phone but YouTube refuses to work. It's just that I'm Russian. And the thing is that in Russia YouTube doesn't work very well. I've tried VPN and Proxy but these things didn't help either (YouTube work with VPN on the actual site).

**Comment by avc1657** [comment]
Install latest stable version (2.8.10) or the latest preview version (2.9.0 preview 3) and see if that fixes the YouTube problem.

**Comment by Calm99999** [comment]
Yeah, you've solved the problem, thanks!
